version: "3"

services:
  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend

    ports:
      - "3000:3000"

    container_name: my_server
    volumes:
      - /usr/src/app/node_modules
      - ./backend:/app

    links:
      - mysql
    depends_on:
      - mysql

  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: my_db
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/

    env_file: .env
